export const stateandcity = {
    "Select State": ["select city"],
    "Andaman and Nicobar Islands": ["select city", "Port Blair"],
    "Andhra Pradesh": ["select city", "Guntur", "Kurnool", "Nellore", "Vijayawada", "Visakhapatnam"].sort(),
    "Arunachal Pradesh": ["select city", "Itanagar", "Naharlagun", "Pasighat", "Roing", "Tawang"].sort(),
    Assam: ["select city", "Dibrugarh", "Guwahati", "Jorhat", "Nagaon", "Silchar"].sort(),
    Bihar: ["select city", "Bhagalpur", "Gaya", "Muzaffarpur", "Patna", "Purnia"].sort(),
    Chandigarh: ["select city", "Chandigarh"],
    Chhattisgarh: ["select city", "Bhilai", "Bilaspur", "Durg", "Korba", "Raipur"].sort(),
    "Dadra and Nagar Haveli": ["select city", "Silvassa"],
    "Daman and Diu": ["select city", "Daman", "Diu"].sort(),
    Goa: ["select city", "Mapusa", "Margao", "Panaji", "Ponda", "Vasco da Gama"].sort(),
    Gujarat: ["select city", "Ahmedabad", "Bhavnagar", "Rajkot", "Surat", "Vadodara"].sort(),
    Haryana: ["select city", "Ambala", "Faridabad", "Gurgaon", "Panipat", "Yamunanagar"].sort(),
    "Himachal Pradesh": ["select city", "Dharamshala", "Kullu", "Mandi", "Shimla", "Solan"].sort(),
    "Jammu and Kashmir": ["select city", "Anantnag", "Baramulla", "Jammu", "Kathua", "Srinagar"].sort(),
    Jharkhand: ["select city", "Bokaro Steel City", "Deoghar", "Dhanbad", "Jamshedpur", "Ranchi"].sort(),
    Karnataka: ["select city", "Bangalore", "Belgaum", "Hubli", "Mangalore", "Mysore"].sort(),
    Kerala: ["select city", "Kochi", "Kollam", "Kozhikode", "Thiruvananthapuram", "Thrissur"].sort(),
    "Madhya Pradesh": ["select city", "Bhopal", "Gwalior", "Indore", "Jabalpur", "Ujjain"].sort(),
    Maharashtra: ["select city", "Aurangabad", "Mumbai", "Nagpur", "Nashik", "Pune"].sort(),
    Manipur: ["select city", "Bishnupur", "Churachandpur", "Imphal", "Senapati", "Thoubal"].sort(),
    Meghalaya: ["select city", "Jowai", "Nongpoh", "Shillong", "Tura", "Williamnagar"].sort(),
    Mizoram: ["select city", "Aizawl", "Champhai", "Lunglei", "Saiha", "Serchhip"].sort(),
    Nagaland: ["select city", "Dimapur", "Kohima", "Mokokchung", "Tuensang", "Wokha"].sort(),
    Odisha: ["select city", "Bhubaneswar", "Brahmapur", "Cuttack", "Rourkela", "Sambalpur"].sort(),
    Puducherry: ["select city", "Karaikal", "Mahe", "Puducherry", "Yanam"].sort(),
    Punjab: ["select city", "Amritsar", "Bathinda", "Jalandhar", "Ludhiana", "Patiala"].sort(),
    Rajasthan: ["select city", "Ajmer", "Bikaner", "Jaipur", "Jodhpur", "Kota"].sort(),
    Sikkim: ["select city", "Gangtok", "Gyalshing", "Mangan", "Namchi", "Singtam"].sort(),
    "Tamil Nadu": ["select city", "Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli"].sort(),
    Telangana: ["select city", "Hyderabad", "Karimnagar", "Nizamabad", "Ramagundam", "Warangal"].sort(),
    Tripura: ["select city", "Agartala", "Belonia", "Dharmanagar", "Kailasahar", "Udaipur"].sort(),
    Uttarakhand: ["select city", "Dehradun", "Haldwani", "Haridwar", "Kashipur", "Roorkee"].sort(),
    "Uttar Pradesh": ["select city", "Agra", "Kanpur", "Lucknow", "Meerut", "Varanasi"].sort(),
    "West Bengal": ["select city", "Asansol", "Bardhaman", "Bankura", "Durgapur", "Kolkata"].sort()
};
