export const stateandcity = {
    "Select State": ["select city"],
    "Andhra Pradesh": ["select city", "Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool"],
    Maharashtra: ["select city", "Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
    "Tamil Nadu": ["select city", "Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
    "Uttar Pradesh": ["select city", "Lucknow", "Kanpur", "Agra", "Varanasi", "Meerut"],
    Assam: ["select city", "Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"],
    "Arunachal Pradesh": ["select city", "Itanagar", "Naharlagun", "Tawang", "Pasighat", "Roing"],
    Manipur: ["select city", "Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Senapati"],
    Nagaland: ["select city", "Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha"],
    "Meghalaya": ["select city", "Shillong", "Tura", "Jowai", "Nongpoh", "Williamnagar"],
    "Mizoram": ["select city", "Aizawl", "Lunglei", "Saiha", "Champhai", "Serchhip"],
    "Tripura": ["select city", "Agartala", "Udaipur", "Dharmanagar", "Kailasahar", "Belonia"],
    "Sikkim": ["select city", "Gangtok", "Namchi", "Mangan", "Gyalshing", "Singtam"],
    "Jammu and Kashmir": ["select city", "Srinagar", "Jammu", "Anantnag", "Baramulla", "Kathua"],
    "Himachal Pradesh": ["select city", "Shimla", "Mandi", "Solan", "Dharamshala", "Kullu"],
    "Punjab": ["select city", "Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda"],
    Haryana: ["select city", "Faridabad", "Gurgaon", "Panipat", "Ambala", "Yamunanagar"],
    "Chandigarh": ["select city", "Chandigarh"],
    Uttarakhand: ["select city", "Dehradun", "Haridwar", "Roorkee", "Haldwani", "Kashipur"],
    "Rajasthan": ["select city", "Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer"],
    Gujarat: ["select city", "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
    "Daman and Diu": ["select city", "Daman", "Diu"],
    "Dadra and Nagar Haveli": ["select city", "Silvassa"],
    Goa: ["select city", "Panaji", "Vasco da Gama", "Margao", "Mapusa", "Ponda"],
    "Madhya Pradesh": ["select city", "Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain"],
    "Chhattisgarh": ["select city", "Raipur", "Bhilai", "Korba", "Bilaspur", "Durg"],
    "Telangana": ["select city", "Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam"],
    "Karnataka": ["select city", "Bangalore", "Mysore", "Hubli", "Mangalore", "Belgaum"],
    "Kerala": ["select city", "Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur"],
    "Puducherry": ["select city", "Puducherry", "Karaikal", "Mahe", "Yanam"],
    "Andaman and Nicobar Islands": ["select city", "Port Blair"],
    "West Bengal": ["select city", "Kolkata", "Asansol", "Siliguri", "Durgapur", "Bardhaman","Bankura"],
    "Jharkhand": ["select city", "Ranchi", "Jamshedpur", "Dhanbad", "Bokaro Steel City", "Deoghar"],
    "Bihar": ["select city", "Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia"],
    "Odisha": ["select city", "Bhubaneswar", "Cuttack", "Rourkela", "Brahmapur", "Sambalpur"],
    "Harayana": ["select city", "Gurugram", "Faridabad", "Panipat", "Ambala", "Yamunanagar"],
    
};
